name: Deploy AiCrateDigger to Lightsail

on:
  push:
    branches:
      - main  # Pipeline only runs when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Deploying application via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/AiCrateDigger
            
            # Pull the latest code from GitHub
            git pull origin main
            
            # Restart the application without shutting down the entire system
            docker compose -f docker-compose.prod.yml up --build -d
            
            # Clean up old unused Docker build images to prevent disk fill
            docker image prune -f